// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA6DDio_AjUC6j3bFuiJ_iiSUTHQVtmn1I',
//     appId: '1:954277256054:android:dca95c01d9440e6a57f857',
//     messagingSenderId: '954277256054',
//     projectId: 'drinkapp-41889',
//     storageBucket: 'drinkapp-41889.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBHYBCucyDw-H6QrEwPd1bcaz_JGkn_QaY',
//     appId: '1:954277256054:ios:b7515fbe8a01e25257f857',
//     messagingSenderId: '954277256054',
//     projectId: 'drinkapp-41889',
//     storageBucket: 'drinkapp-41889.appspot.com',
//     androidClientId: '954277256054-2ofq2a8dolnqlh4ce37org5t3vhcrgcf.apps.googleusercontent.com',
//     iosClientId: '954277256054-7n6kj4u8ti0us8m7c509o7qb1ag4g1af.apps.googleusercontent.com',
//     iosBundleId: 'com.example.getxapp',
//   );

// }